### ISSUE TITLE
[1.16.5] Grid Tool-Repairation with multiples items at the time bug

### ISSUE THREAD

**Issue by Fireztonez** [BlakeBr0/PickleTweaks2#69] opened 2021-02-27 00:58 UTC
**Describe the bug**
When you place the tool you want to repair in your crafting table, and add 2 or more items question to repair a tool, the crafting result desperate. You have to take back the tool from the crafting grid and place back on it question to being able to do the reparation.

With Pickle Tweaks for Minecraft 1.12.2, we could place the tool in question and items 1 to 1 to repair it without having to click again on the tool to pick it up and replace it.

**To Reproduce**
Place your tool on your grid, and place 2 items for repair the tool.

**Expected behavior**
Being able to see the result and repair directly, without pick and place back the tool in the grid.

**Screenshots / Scripts / Logs**
When you place the tool before the ingredient to repair:
![pickletweak_reparation_bug](https://user-images.githubusercontent.com/19277301/109370024-b269a080-786c-11eb-9e43-374b66a5684f.png)

When you place the tool after (Or Pick and place back on the grid):
![pickletweak_reparation_bug-2](https://user-images.githubusercontent.com/19277301/109370059-c44b4380-786c-11eb-9f3c-4187efc08f4a.png)

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.0.43
 - Cucumber: 4.1.8
 - Pickle Tweaks: 5.2.1

**Comment by Darkosto** [comment] 2021-03-01 18:37
Yes. I too experience this issue. Pls show me the way how to fix

**Comment by BlakeBr0** [comment] 2021-03-27 20:25
I couldn't reproduce this in dev or in a small modpack I have, so I'm guessing there's a mod conflict somewhere?

**Comment by Darkosto** [comment] 2021-03-28 02:08
We got it figured out. Looks like it was FastWorkbench causing it. Shadows has fixed it up and released last week so you should be good to close this issue. Thanks!

**Closed as completed** 2021-03-28 20:13 UTC
Labels: Bug, 1.16
