### ISSUE TITLE
Pickle Tweaks - Features - tool_info_tooltip constantly updates after OreExcavation

### ISSUE THREAD

**Issue by knoxhack** [BlakeBr0/PickleTweaks2#57] opened 2020-08-17 20:06 UTC
**Describe the bug**
Happened to me now several times -
I assume the issue to be a combination between Picke Tweaks & OreExcavation; Randomly after Veinmining this issue can occur:
https://www.youtube.com/watch?v=RRlY2CXiC_U

**To Reproduce**
"
Whats happening is that "Blocks Broken:" constantly adds more and more blocks despite no further blocks being broken.
https://cdn.discordapp.com/attachments/696489474711879731/744323055475490866/unknown.png

This happens to all Tools  using the tool_info_tooltip feature from Picke Tweaks as soon you take them into your hand once the issue occured for the first time, regardless of which tool has been used to cause this issue in the first place (Mined asteroids; Axe will also add up "Blocks Broken:")
 Relogging/Restarting does not solve the issue.
Turning off 'tool_info_tooltip' in the PickleTweaks seems to solve the issue for my SP World - yet not on the Testserver because I assume the stat to be tracked serverside regardless of Clients ability to see the stats.
Hope this can be fixed 🤷 
"

**Screenshots / Scripts / Logs**
Please add your logs and scripts (if applicable).

**Versions (please complete the following information):**
 - Minecraft: 1.12.2
 - Forge: 14.23.5.2854
 - Cucumber: Cucumber-1.12.2-1.1.3
 - Pickle Tweaks: PickleTweaks-1.12.2-2.1.3

**Comment by knoxhack** [comment] 2020-08-17 20:06
https://github.com/NFINIT-Development/Astroblock2/issues/9

**Comment by BlakeBr0** [comment] 2020-08-20 00:18
Interesting. The number is incremented during the BlockBreak event, so I would assume that something is causing that to be called indefinitely. Seems like a pretty serious issue if that's the case.  I don't see how this could be caused by Pickle Tweaks itself, especially since this has never come up before.

**Comment by Enderized** [comment] 2020-08-25 16:14
Another thing a friend and I noticed; that this issue will stop once you take damage which makes things even weirder - like why would it stop upon taking damage? ._.

**Comment by BlakeBr0** [comment] 2021-01-27 10:02
I'm going to close this since I'm no longer supporting the 1.12 version.

**Closed as completed by BlakeBr0** 2021-01-27 10:02 UTC
Labels: Bug
