### ISSUE TITLE
Crafting Grid Tool Repair doesn't work for tools with container items

### ISSUE THREAD

**Issue by Fireztonez** [BlakeBr0/PickleTweaks2#70] opened 2021-03-08 09:58 UTC
**Describe the bug**
I try to add somes custom grid repair for the tools from No Tree Punching, using "notreepunching:flint_shard" and for somes reason, this work for the shovel, the pickaxe and the hoe, but doesn't work with the axe and the blade.

**To Reproduce**
- Install NoTreePunching with Pickle Tweaks
- Add the override config:
```["notreepunching:flint_knife=notreepunching:flint_shard@1.0", "notreepunching:flint_axe=notreepunching:flint_shard@1.0", "notreepunching:flint_shovel=notreepunching:flint_shard@0.333", "notreepunching:flint_hoe=notreepunching:flint_shard@0.5", "notreepunching:flint_pickaxe=notreepunching:flint_shard@0.25"]```
- Try to repair your tools.

**Expected behavior**
- We should be able to add any type of tools with any type of material for repair.

**Screenshots / Scripts / Logs**
Config file: https://gist.github.com/Fireztonez/6abb508e03f665b705f550d45dcab119
Logs: https://gist.github.com/Fireztonez/dbe67f7a4ea4d0522d87767ff7fb29d1

**Versions (please complete the following information):**
 - Minecraft: 1.16.5
 - Forge: 36.0.46
 - Cucumber: 4.1.8
 - Pickle Tweaks: 5.2.1
 - No Tree Punching: 4.1.2

**Comment by BlakeBr0** [comment] 2021-04-04 22:30
So I think the issue is that those two items have container items. Currently the grid repair recipe doesn't work for those, though I'll probably look into changing that.

**Comment by BlakeBr0** [comment] 2021-04-05 00:37
Fixed by https://github.com/BlakeBr0/PickleTweaks/commit/9430dfb0304b789a5e452eb8554ec868258fdfd4

**Closed as completed by BlakeBr0** 2021-04-05 00:37 UTC
Labels: Bug, 1.16
